import numpy as np, itertools, sys, time
from lib import *
from proto import *


def reflect(sym_op, site):
    return Sym({S: (-v if site in S else v) for S, v in sym_op.items()})


def omega_product_check(out, keep, blocks):
    """is `out` exactly the product of Omega on each block (x) I/2 on leftovers?"""
    nk = len(keep)
    tgt = Sym({frozenset(): 2.0 ** (-nk)})
    for b in blocks:
        tgt = sym_mul(tgt, sym_add(sym_I(), sym_scale(sym_J(b), -1.0)))
    diff = sym_add(tgt, sym_scale(out, -1.0))
    return (not diff), max([abs(v) for v in diff.values()] + [0.0])


def run_case(name, S, expect_blocks_fn=None, dense=True, show=True, branches=None,
             dense_limit=None):
    print("=" * 78)
    print(name)
    print("  holders=%d  U(measured)=%s  W(extra traced)=%s  V(kept holders)=%s"
          % (S.H, S.U, S.W, S.V))
    print("  aux pairs (holders)=%s  -> aux sites %s   total rebits n=%d"
          % (S.auxpairs, [(S.aux[u], S.aux[v]) for u, v in S.auxpairs], S.n))
    print("  code words: " + ", ".join("%s(s=%+d)" % (sorted(w), s) for w, b, s in S.words))
    Us = S.U
    allbr = list(itertools.product([1, -1], repeat=len(Us))) if branches is None else branches
    nfail = 0
    probs = []
    verdicts = []
    for bi, bvals in enumerate(allbr):
        x = dict(zip(Us, bvals))
        pB, outB = engineB(S, x)
        pred, diag, aligned = predict(S, x, verbose=(show and bi == 0))
        probs.append(pB)
        # ---- engine A cross-check
        agree_A = None
        if dense and (dense_limit is None or bi < dense_limit):
            pA, outAd, keep = engineA(S, x)
            outA = dense_to_sym(outAd, keep)
            agree_A = (abs(pA - pB) < 1e-9) and (not sym_add(outA, sym_scale(outB, -1.0)))
        # ---- prediction check (unnormalised, up to the 2^{...} bookkeeping)
        if abs(pB) < 1e-13:
            verdicts.append((bvals, pB, "ZERO-PROBABILITY BRANCH", agree_A))
            continue
        nrm = normalise(outB, len(S.keep))
        pnrm = normalise(pred, len(S.keep))
        pred_ok = (pnrm is not None) and (not sym_add(nrm, sym_scale(pnrm, -1.0)))
        # ---- structure: is the surviving V-group generated by disjoint pairs?
        Vstrings = set(k for k in support_group(nrm))
        auxsites = set(S.aux.values())
        Vpart = set(frozenset(k - auxsites) for k in Vstrings)
        okpairs, why = is_disjoint_pair_generated(Vpart)
        # ---- blocks + reflections
        blocks = [frozenset(b) for b in Vpart if len(b) == 2]
        blocks += [frozenset([S.aux[u], S.aux[v]]) for u, v in S.auxpairs]
        cur = nrm
        flips = []
        if okpairs:
            for b in blocks:
                c = cur.get(b, 0.0) * 2.0 ** len(S.keep)
                if c > 0.5:            # +1 -> needs a flip to reach Omega
                    v0 = sorted(b)[0]
                    cur = reflect(cur, v0); flips.append(v0)
            prod_ok, err = omega_product_check(cur, S.keep, blocks)
        else:
            prod_ok, err = False, float('nan')
        verdicts.append((bvals, pB, dict(pred_ok=pred_ok, aligned=aligned, okpairs=okpairs,
                                         why=why, prod_ok=prod_ok, flips=flips), agree_A))
        if not (pred_ok and prod_ok): nfail += 1
    print("  branch probabilities: min=%.6g max=%.6g  (uniform=%s)  sum=%.10g"
          % (min(probs), max(probs), np.allclose(probs, probs[0]), sum(probs)))
    okA = all(v[3] in (True, None) for v in verdicts)
    print("  engine A == engine B on every branch: %s" % okA)
    # summary
    good = [v for v in verdicts if isinstance(v[2], dict) and v[2]['pred_ok'] and v[2]['prod_ok']]
    print("  branches: %d total, %d exact Omega-product, %d FAIL" % (len(verdicts), len(good), nfail))
    if nfail:
        for bvals, p, d, aA in verdicts:
            if isinstance(d, dict) and not (d['pred_ok'] and d['prod_ok']):
                print("    FAIL x=%s p=%.5f  pred_ok=%s aligned=%s disjoint-pairs=%s (%s) product=%s"
                      % (bvals, p, d['pred_ok'], d['aligned'], d['okpairs'], d['why'], d['prod_ok']))
                break
    else:
        d0 = verdicts[0][2]
        print("  flips on branch %s: %s" % (verdicts[0][0], d0['flips']))
    return verdicts, S
