"""General closed form (valid with NO alignment hypothesis) + exhaustive sweep
that isolates exactly which hypotheses the Omega-product claim needs."""
import sys, itertools, random
from cases import *


def predict_general(S, x):
    """rho_out = 2^{|W|} 2^{-H} SUM_{c: supp(c) subset U u V}
                  s_c (-1)^{|D_c|} h_c  J_{R_c} (x) TENSOR_j alpha_j(c)
       alpha_j = Omega_j (no holder of pair j in D)
               = -Omega_j (both holders in D)
               = (1/4)(J_a + J_a')  (exactly one, the one in D having aux site a)"""
    tot = Sym()
    for w, bits, s in S.words:
        D = frozenset(w) & frozenset(S.U)
        R = frozenset(w) - frozenset(S.U)
        if R & frozenset(S.W):
            continue                       # not covered -> dies in the trace
        h = 1.0
        for u in D: h *= x[u]
        term = Sym({frozenset(R): s * ((-1.0) ** len(D)) * h})
        for (u, v) in S.auxpairs:
            a, b = S.aux[u], S.aux[v]
            inD = [q for q in (u, v) if q in D]
            Om = sym_add(sym_scale(sym_I(), 0.25), sym_scale(sym_J([a, b]), -0.25))
            if len(inD) == 2:
                aj = sym_scale(Om, -1.0)
            elif len(inD) == 0:
                aj = Om
            else:
                aa = S.aux[inD[0]]
                aj = sym_scale(sym_add(sym_J([a]), sym_J([b])), 0.25) if aa == a else \
                     sym_scale(sym_add(sym_J([b]), sym_J([a])), 0.25)
                # J_{aa} . Omega_j = (1/4)(J_a + J_b) either way -- verify below
            term = sym_mul(term, aj)
        tot = sym_add(tot, term)
    return sym_scale(tot, (2.0 ** len(S.W)) * (2.0 ** (-S.H)))


def structure_flags(S, x):
    """H2 = every covered codeword's measured support is a union of aux pairs
       H3 = the R-image code is generated by pairwise-disjoint weight-2 words"""
    H2 = True
    Rs = set()
    for w, bits, s in S.words:
        D = frozenset(w) & frozenset(S.U)
        R = frozenset(w) - frozenset(S.U)
        if R & frozenset(S.W):
            continue
        for (u, v) in S.auxpairs:
            if ((u in D) + (v in D)) == 1: H2 = False
        Rs.add(frozenset(R))
    H3, why = is_disjoint_pair_generated(Rs)
    return H2, H3, why, Rs


def omega_product_after_flips(S, out):
    """try to reach TENSOR Omega over pair blocks by single-rebit reflections."""
    nrm = normalise(out, len(S.keep))
    if nrm is None: return None
    auxs = set(S.aux.values())
    Vpart = set(frozenset(k - auxs) for k in support_group(nrm))
    ok, why = is_disjoint_pair_generated(Vpart)
    if not ok: return False
    blocks = [frozenset(b) for b in Vpart if len(b) == 2]
    blocks += [frozenset([S.aux[u], S.aux[v]]) for u, v in S.auxpairs]
    cur = nrm
    for b in blocks:
        if cur.get(b, 0.0) * 2.0 ** len(S.keep) > 0.5:
            cur = Sym({T: (-v if sorted(b)[0] in T else v) for T, v in cur.items()})
    tgt = Sym({frozenset(): 2.0 ** (-len(S.keep))})
    for b in blocks:
        tgt = sym_mul(tgt, sym_add(sym_I(), sym_scale(sym_J(b), -1.0)))
    return not sym_add(tgt, sym_scale(cur, -1.0))


# ============================ EXHAUSTIVE-ISH SWEEP ============================
random.seed(20260812)
H = 7
auxpairs = [(3, 4), (5, 6)]
target = [0, 1]
c1 = frozenset([0, 1, 3, 4, 5, 6])          # the descended codeword
holders = list(range(H))

stats = dict(n=0, formula_bad=0, prod=0, noprod=0, zerobranch=0)
table = {}
cases_examined = []
# all even-weight second generators
for r in (2, 4, 6):
    for c2 in itertools.combinations(holders, r):
        c2 = frozenset(c2)
        if c2 in (frozenset(), c1): continue
        for q2 in (0, 1):
            S = Setup(H=H, auxpairs=auxpairs, gens=[sorted(c1), sorted(c2)], qvals=[0, q2])
            H2, H3, why, Rs = structure_flags(S, {u: 1 for u in S.U})
            allbr_prod = True
            formula_ok = True
            zero = 0
            for bvals in itertools.product([1, -1], repeat=len(S.U)):
                xx = dict(zip(S.U, bvals))
                pB, outB = engineB(S, xx)
                pg = predict_general(S, xx)
                if sym_add(outB, sym_scale(pg, -1.0)): formula_ok = False
                if abs(pB) < 1e-13:
                    zero += 1; continue
                if omega_product_after_flips(S, outB) is not True: allbr_prod = False
            stats['n'] += 1
            if not formula_ok: stats['formula_bad'] += 1
            if zero: stats['zerobranch'] += 1
            key = (H2, H3, allbr_prod)
            table[key] = table.get(key, 0) + 1
            if allbr_prod: stats['prod'] += 1
            else: stats['noprod'] += 1
            cases_examined.append((sorted(c2), q2, H2, H3, allbr_prod, zero, why))

print("SWEEP over all even second generators c2 (H=7, aux pairs (3,4),(5,6),")
print("descended codeword c1={0,1,3,4,5,6}, target {0,1}), both sign choices.")
print("  setups examined              : %d" % stats['n'])
print("  general closed form MISMATCH : %d   <-- must be 0" % stats['formula_bad'])
print("  Omega-product on all branches: %d" % stats['prod'])
print("  Omega-product FAILS          : %d" % stats['noprod'])
print("  setups with a zero-probability branch: %d" % stats['zerobranch'])
print("\n  (H2 aux-pair-aligned, H3 R-image disjoint-pair-generated) -> product?")
for k in sorted(table): print("     H2=%-5s H3=%-5s  product=%-5s : %d setups" % (k[0], k[1], k[2], table[k]))

bad = [c for c in cases_examined if (c[2] and c[3]) != c[4]]
print("\n  setups where (H2 and H3) != product:", len(bad))
for b in bad[:10]: print("     c2=%s q=%d H2=%s H3=%s prod=%s zero=%d %s" % b)

print("\n  sample of FAILING setups:")
shown = 0
for c in cases_examined:
    if not c[4] and shown < 6:
        print("     c2=%-22s q=%d  H2=%-5s H3=%-5s  reason: %s" % (str(c[0]), c[1], c[2], c[3], c[6]))
        shown += 1

# zero-probability branch demo
print("\nZERO-PROBABILITY BRANCH DEMO: code containing a word inside the measured set")
Sz = Setup(H=7, auxpairs=[(3, 4), (5, 6)], gens=[[0, 1, 3, 4, 5, 6], [3, 4, 5, 6]], qvals=[0, 0])
ps = []
for bvals in itertools.product([1, -1], repeat=4):
    pB, outB = engineB(Sz, dict(zip(Sz.U, bvals)))
    ps.append((bvals, round(pB, 6)))
print("  code words:", [sorted(w) for w, b, s in Sz.words])
print("  branch probabilities:", ps[:8], "...")
print("  #zero-probability branches: %d of 16   -> branches are NOT uniform/complete"
      % sum(1 for b, p in ps if abs(p) < 1e-12))
