import sys, itertools, random
from cases import *
from t4_general import predict_general, structure_flags, omega_product_after_flips


# --- GF(2) support algebra for the EFFECTIVE-code biconditional ---
def _echelon(keys):
    basis = []
    for k in keys:
        v = set(k)
        changed = True
        while changed and v:
            changed = False
            for b in basis:
                if b and min(b) in v:
                    v ^= b
                    changed = True
        if v:
            basis.append(v)
    return basis


def _reduces_to_empty(k, basis):
    v = set(k)
    changed = True
    while changed and v:
        changed = False
        for b in basis:
            if b and min(b) in v:
                v ^= b
                changed = True
    return not v


def pair_generated(keys):
    """Is the GF(2) span of the support sets generated by pairwise-
    disjoint weight-2 elements? (= the surviving algebra is a product
    of sharp pair blocks)"""
    keys = [frozenset(k) for k in keys if k]
    if not keys:
        return True
    basis = _echelon(keys)
    if len(basis) > 16:
        raise RuntimeError("span too large for enumeration")
    span = set()
    for r in range(1, len(basis) + 1):
        for comb in itertools.combinations(range(len(basis)), r):
            v = set()
            for i in comb:
                v ^= basis[i]
            if v:
                span.add(frozenset(v))
    w2 = [s for s in span if len(s) == 2]
    for i in range(len(w2)):
        for j in range(i + 1, len(w2)):
            if len(w2[i] & w2[j]) == 1:
                return False
    b2 = _echelon(w2)
    return all(_reduces_to_empty(k, b2) for k in keys)


random.seed(7)
H = 8                      # holders 0,1 target ; 2,3,4,5 measured ; 6,7 spare
auxpairs = [(2, 3), (4, 5)]
c1 = [0, 1, 2, 3, 4, 5]
n_setup = 0; mism = 0; fwd_viol = 0; eff_viol = 0; exception_cls = 0; marg_bad = 0; psd_bad = 0; prod_yes = 0; nbr = 0
seen = set()
trials = 0
while n_setup < 120 and trials < 4000:
    trials += 1
    k = random.choice([2, 3])
    gens = [c1]
    for _ in range(k - 1):
        while True:
            w = [h for h in range(H) if random.random() < 0.45]
            if len(w) % 2 == 0 and w: break
        gens.append(sorted(w))
    key = tuple(map(tuple, gens))
    if key in seen: continue
    seen.add(key)
    q = [random.randint(0, 1) for _ in gens]
    try:
        S = Setup(H=H, auxpairs=auxpairs, gens=gens, qvals=q)
    except AssertionError:
        continue
    n_setup += 1
    H2, H3, why, Rs = structure_flags(S, {u: 1 for u in S.U})
    allprod = True
    effkeys = set()
    killed_sector = False
    for bvals in itertools.product([1, -1], repeat=4):
        xx = dict(zip(S.U, bvals))
        pB, outB = engineB(S, xx)
        pg = predict_general(S, xx)
        if sym_add(outB, sym_scale(pg, -1.0)): mism += 1
        if abs(pB) < 1e-13:
            killed_sector = True
            continue
        nbr += 1
        effkeys |= {frozenset(k) for k, c in outB.items()
                    if k and abs(c) > 1e-12}
        nrm = normalise(outB, len(S.keep))
        if omega_product_after_flips(S, outB) is not True: allprod = False
        M = sym_to_dense(nrm, len(S.keep), sites_order=S.keep)
        if np.linalg.eigvalsh(M).min() < -1e-10: psd_bad += 1
        others = [s for s in S.keep if s not in (0, 1)]
        m = sym_ptrace(nrm, others); m = sym_scale(m, 1.0 / sym_trace(m, 2))
        if abs(abs(m.get(frozenset([0, 1]), 0.0) * 4) - 1.0) > 1e-10: marg_bad += 1
    if allprod: prod_yes += 1
    formal = (H2 and H3)
    if formal and not allprod:
        fwd_viol += 1                       # sufficiency must never fail
    if pair_generated(effkeys) != allprod:
        eff_viol += 1                       # effective-code iff must hold
    if allprod and not formal:
        exception_cls += 1                  # sign-killed exception class
        if not killed_sector:
            eff_viol += 1                   # exception without kills = real bug

print("RANDOM SWEEP, H=8 holders (+4 aux = 12 rebits), codes of dim 2-3, random signs")
print("  setups                                  : %d  (branches: %d)" % (n_setup, nbr))
print("  general closed-form mismatches          : %d   <-- must be 0" % mism)
print("  (H2 and H3) => product failures         : %d   <-- must be 0 (sufficiency)" % fwd_viol)
print("  effective-code iff violations           : %d   <-- must be 0" % eff_viol)
print("    (product <=> surviving support algebra is pair-generated)")
print("  sign-killed exception class (product    : %d       (known class: formal" % exception_cls)
print("   holds while formal H2&H3 fail)                     conditions evaluated on")
print("                                                      the full code; offending")
print("                                                      words killed on every")
print("                                                      surviving branch)")
print("  setups achieving the Omega-product      : %d / %d" % (prod_yes, n_setup))
print("  positivity failures                     : %d" % psd_bad)
print("  target-pair marginal not sharp +-Omega  : %d   <-- must be 0" % marg_bad)
if mism or fwd_viol or eff_viol or psd_bad or marg_bad:
    sys.exit(1)
